# 填写完毕后，将本文件重命名为`config.yml`

bot_basic: # Bot 基础类信息
    bot_name: "" # Bot 名称: string
    bot_name_argument: "" # 用于传参的 Bot 名称（通常使用英文）: string
    bot_owner: [""] # Bot 所有者: list[string]
    bot_repo: "" # Bot 对应GitHub仓库: string 
    bot_notice: # Bot 事件通知
        "": 
            "" # Bot QQ号: Bot 通知群号 (string: string)
    proxy: "" # 代理服务器

github: # GitHub 相关配置
    web_path: "" # Webhook 接收路径
    github_personal_token: "" # Rest API Token

jx3: # 剑网3 相关配置
    api: # JX3API/推栏API
        token: "" # JX3API Token (V1/V2)
        token_v2: "" # JX3API Token (V2)
        ticket: "" # 推栏 Token
        url: "" # JX3API 地址(不带斜杠)
        enable: false # 是否启用JX3API
        # 启用之后：沙盘、招募、榜单可用，奇遇统计时间补全
    ws:
        url: "" # JX3API WebSocket 地址
        token: "" # JX3API WebSocket Token
hidden:
    offcial_token: "" # Inkar Suki 官方API Token 非官方Bot请留空